name: CI

on:
  push:
    branches: [ lab5 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Восстанавливаем зависимости
      - name: Restore dependencies
        run: dotnet restore Hotel/Hotel.csproj

      # Сборка решения
      - name: Build
        run: dotnet build Hotel/Hotel.csproj --configuration Release --no-restore